import = [".config/alacritty/theme/github_light.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Light"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0
